
modLoader="javafml" 

loaderVersion="[34,)"
license="All rights reserved"

[[mods]]
    modId="craftandhunt"
    displayName="Craft and Hunt"
    description="Hunt stuff, craft stuff, hunt stuff, upgrade stuff! A mod that focuses on expanding vanilla (and some cross-mod support) mobs, armor, tools, and blocks!"
    version="2.3.0"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/craft-and-hunt"
    authors="Aavri, CandyCaneCazoo"
	
	
[[dependencies.craftandhunt]]
    modId="forge"
    mandatory=true
    versionRange="[34.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.craftandhunt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"
