
modLoader="javafml" 

loaderVersion="[34,)"
license="All rights reserved"

[[mods]]
    modId="craftandhunt"
    displayName="${mod_name}"
    description="${mod_description}"
    version="${mod_version}"
    displayURL="${mod_url}"
    authors="${mod_author}"
	
	
[[dependencies.craftandhunt]]
    modId="forge"
    mandatory=true
    versionRange="[34.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.craftandhunt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"
